### PR TITLE
Make year configurable, clean up some URL variables

### PR DESCRIPTION
**Pull request by coffbr01**

### CODE REVIEW

**Comment by nostlie** [comment]
looks fishy

**Comment by coffbr01** [comment]
@nostlie you look fishy

**Comment by nostlie** [comment]
I'm going to need to see comments in your code. Make sure the official code review committee has reviewed. Align it to our coding standards (tabs not spaces). Insert the official copyright along with the year in each affected file. Make sure that all automated tests pass for all versions of Ruby, and then write it all over again in Python because the lead developer doesn't like Ruby.

**Comment by coffbr01** [comment]
In the spirit of collaborative programming, I'll leave those changes to you. Feel free to open another PR, and we can close this one once you're done.

**Comment by nostlie** [comment]
Oooo, I'm afraid we have a limit of 1 PR open at a time. Sorry.

**Pull request merged**
